package com.github.artpar.pragma.jetbrains.mcp

data class TargetApi(
    val category: String,
    val className: String,
    val methods: List<TargetMethod> = emptyList(),
    val fields: List<String> = emptyList(),
    val requiredInPlatformRuntime: Boolean = true,
)

data class TargetMethod(
    val name: String,
    val parameterTypes: List<String>? = null,
    val static: Boolean? = null,
)

val targetApiMatrix: List<TargetApi> = listOf(
    TargetApi(
        category = "application-threading",
        className = "com.intellij.openapi.application.ApplicationManager",
        methods = listOf(TargetMethod("getApplication", emptyList(), static = true)),
    ),
    TargetApi(
        category = "application-threading",
        className = "com.intellij.openapi.application.Application",
        methods = listOf(
            TargetMethod("runReadAction", listOf("java.lang.Runnable")),
            TargetMethod("runReadAction", listOf("com.intellij.openapi.util.Computable")),
            TargetMethod("runWriteAction", listOf("java.lang.Runnable")),
            TargetMethod("invokeLater", listOf("java.lang.Runnable")),
            TargetMethod("invokeAndWait", listOf("java.lang.Runnable")),
            TargetMethod("isDispatchThread", emptyList()),
            TargetMethod("isReadAccessAllowed", emptyList()),
            TargetMethod("isWriteAccessAllowed", emptyList()),
        ),
    ),
    TargetApi(
        category = "application-threading",
        className = "com.intellij.openapi.command.WriteCommandAction",
        methods = listOf(
            TargetMethod("runWriteCommandAction", listOf("com.intellij.openapi.project.Project", "java.lang.Runnable"), static = true),
            TargetMethod("runWriteCommandAction", listOf("com.intellij.openapi.project.Project", "com.intellij.openapi.util.Computable"), static = true),
        ),
    ),
    TargetApi(
        category = "project-model",
        className = "com.intellij.openapi.project.Project",
        methods = listOf(TargetMethod("getName"), TargetMethod("getBasePath"), TargetMethod("isDisposed")),
    ),
    TargetApi(
        category = "project-model",
        className = "com.intellij.openapi.project.DumbService",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("isDumb", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("isDumb", emptyList()),
        ),
    ),
    TargetApi(
        category = "project-model",
        className = "com.intellij.openapi.roots.ProjectRootManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getFileIndex", emptyList()),
            TargetMethod("getContentRoots", emptyList()),
            TargetMethod("getContentSourceRoots", emptyList()),
            TargetMethod("getProjectSdk", emptyList()),
        ),
    ),
    TargetApi(
        category = "editor-documents",
        className = "com.intellij.openapi.fileEditor.FileEditorManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getSelectedTextEditor", emptyList()),
            TargetMethod("openTextEditor", listOf("com.intellij.openapi.fileEditor.OpenFileDescriptor", "boolean")),
            TargetMethod("openFile", listOf("com.intellij.openapi.vfs.VirtualFile", "boolean")),
            TargetMethod("closeFile", listOf("com.intellij.openapi.vfs.VirtualFile")),
            TargetMethod("getOpenFiles", emptyList()),
        ),
    ),
    TargetApi(
        category = "editor-documents",
        className = "com.intellij.openapi.fileEditor.FileDocumentManager",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("getDocument", listOf("com.intellij.openapi.vfs.VirtualFile")),
            TargetMethod("saveDocument", listOf("com.intellij.openapi.editor.Document")),
            TargetMethod("saveAllDocuments", emptyList()),
        ),
    ),
    TargetApi(
        category = "editor-documents",
        className = "com.intellij.openapi.editor.Document",
        methods = listOf(
            TargetMethod("getText", emptyList()),
            TargetMethod("getTextLength", emptyList()),
            TargetMethod("setText", listOf("java.lang.CharSequence")),
            TargetMethod("replaceString", listOf("int", "int", "java.lang.CharSequence")),
            TargetMethod("insertString", listOf("int", "java.lang.CharSequence")),
            TargetMethod("getLineCount", emptyList()),
            TargetMethod("getLineStartOffset", listOf("int")),
            TargetMethod("getLineEndOffset", listOf("int")),
            TargetMethod("getModificationStamp", emptyList()),
        ),
    ),
    TargetApi(
        category = "vfs",
        className = "com.intellij.openapi.vfs.LocalFileSystem",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("refreshAndFindFileByPath", listOf("java.lang.String")),
            TargetMethod("refreshAndFindFileByNioFile", listOf("java.nio.file.Path")),
        ),
    ),
    TargetApi(
        category = "vfs",
        className = "com.intellij.openapi.vfs.VirtualFile",
        methods = listOf(
            TargetMethod("getPath", emptyList()),
            TargetMethod("getUrl", emptyList()),
            TargetMethod("getName", emptyList()),
            TargetMethod("getChildren", emptyList()),
            TargetMethod("contentsToByteArray", emptyList()),
            TargetMethod("setBinaryContent", listOf("[B")),
            TargetMethod("isDirectory", emptyList()),
            TargetMethod("isWritable", emptyList()),
            TargetMethod("isValid", emptyList()),
            TargetMethod("delete", listOf("java.lang.Object")),
            TargetMethod("findChild", listOf("java.lang.String")),
        ),
    ),
    TargetApi(
        category = "editor-documents",
        className = "com.intellij.openapi.editor.Editor",
        methods = listOf(
            TargetMethod("getDocument", emptyList()),
            TargetMethod("getCaretModel", emptyList()),
            TargetMethod("getSelectionModel", emptyList()),
            TargetMethod("isDisposed", emptyList()),
        ),
    ),
    TargetApi(
        category = "editor-documents",
        className = "com.intellij.openapi.editor.CaretModel",
        methods = listOf(TargetMethod("getOffset", emptyList()), TargetMethod("getLogicalPosition", emptyList())),
    ),
    TargetApi(
        category = "editor-documents",
        className = "com.intellij.openapi.editor.SelectionModel",
        methods = listOf(
            TargetMethod("hasSelection", emptyList()),
            TargetMethod("getSelectedText", emptyList()),
            TargetMethod("getSelectionStart", emptyList()),
            TargetMethod("getSelectionEnd", emptyList()),
            TargetMethod("setSelection", listOf("int", "int")),
        ),
    ),
    TargetApi(
        category = "psi-navigation",
        className = "com.intellij.psi.PsiManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("findFile", listOf("com.intellij.openapi.vfs.VirtualFile")),
            TargetMethod("findDirectory", listOf("com.intellij.openapi.vfs.VirtualFile")),
        ),
    ),
    TargetApi(
        category = "psi-navigation",
        className = "com.intellij.psi.PsiDocumentManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getPsiFile", listOf("com.intellij.openapi.editor.Document")),
            TargetMethod("getDocument", listOf("com.intellij.psi.PsiFile")),
            TargetMethod("commitDocument", listOf("com.intellij.openapi.editor.Document")),
        ),
    ),
    TargetApi(
        category = "psi-navigation",
        className = "com.intellij.psi.PsiElement",
        methods = listOf(
            TargetMethod("findElementAt", listOf("int")),
            TargetMethod("findReferenceAt", listOf("int")),
            TargetMethod("getReference", emptyList()),
            TargetMethod("getReferences", emptyList()),
            TargetMethod("getText", emptyList()),
            TargetMethod("getTextRange", emptyList()),
            TargetMethod("replace", listOf("com.intellij.psi.PsiElement")),
            TargetMethod("delete", emptyList()),
        ),
    ),
    TargetApi(
        category = "search-indexes",
        className = "com.intellij.psi.search.GlobalSearchScope",
        methods = listOf(
            TargetMethod("projectScope", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("allScope", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("fileScope", listOf("com.intellij.psi.PsiFile"), static = true),
            TargetMethod("filesScope", listOf("com.intellij.openapi.project.Project", "java.util.Collection"), static = true),
        ),
    ),
    TargetApi(
        category = "search-indexes",
        className = "com.intellij.psi.search.FilenameIndex",
        methods = listOf(
            TargetMethod("getVirtualFilesByName", listOf("java.lang.String", "com.intellij.psi.search.GlobalSearchScope"), static = true),
            TargetMethod("getFilesByName", listOf("com.intellij.openapi.project.Project", "java.lang.String", "com.intellij.psi.search.GlobalSearchScope"), static = true),
            TargetMethod("processFilesByName"),
        ),
    ),
    TargetApi(
        category = "search-indexes",
        className = "com.intellij.psi.search.PsiSearchHelper",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("processElementsWithWord", listOf("com.intellij.psi.search.TextOccurenceProcessor", "com.intellij.psi.search.SearchScope", "java.lang.String", "short", "boolean")),
            TargetMethod("processAllFilesWithWord"),
        ),
    ),
    TargetApi(
        category = "search-indexes",
        className = "com.intellij.psi.search.searches.ReferencesSearch",
        methods = listOf(
            TargetMethod("search", listOf("com.intellij.psi.PsiElement"), static = true),
            TargetMethod("search", listOf("com.intellij.psi.PsiElement", "com.intellij.psi.search.SearchScope"), static = true),
            TargetMethod("searchOptimized", static = true),
        ),
    ),
    TargetApi(
        category = "actions",
        className = "com.intellij.openapi.actionSystem.ActionManager",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("getAction", listOf("java.lang.String")),
            TargetMethod("getActionIdList", listOf("java.lang.String")),
            TargetMethod("tryToExecute"),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.PluginManagerCore",
        methods = listOf(
            TargetMethod("getPlugins", emptyList(), static = true),
            TargetMethod("getLoadedPlugins", emptyList(), static = true),
            TargetMethod("findPlugin", listOf("com.intellij.openapi.extensions.PluginId"), static = true),
            TargetMethod("isPluginInstalled", listOf("com.intellij.openapi.extensions.PluginId"), static = true),
            TargetMethod("getBuildNumber", emptyList(), static = true),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.PluginEnabler",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("isDisabled", listOf("com.intellij.openapi.extensions.PluginId")),
            TargetMethod("enable", listOf("java.util.Collection")),
            TargetMethod("disable", listOf("java.util.Collection")),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.DynamicPlugins",
        methods = listOf(
            TargetMethod("loadPlugin", listOf("com.intellij.ide.plugins.IdeaPluginDescriptorImpl", "com.intellij.openapi.project.Project")),
            TargetMethod("unloadPlugin", listOf("com.intellij.ide.plugins.IdeaPluginDescriptorImpl")),
            TargetMethod("checkCanUnloadWithoutRestart", listOf("com.intellij.ide.plugins.IdeaPluginDescriptorImpl")),
            TargetMethod("allowLoadUnloadWithoutRestart", listOf("com.intellij.ide.plugins.IdeaPluginDescriptorImpl"), static = true),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.PluginInstaller",
        methods = listOf(
            TargetMethod("prepareToUninstall", listOf("com.intellij.ide.plugins.IdeaPluginDescriptorImpl"), static = true),
            TargetMethod("installAfterRestart", listOf("com.intellij.ide.plugins.IdeaPluginDescriptor", "java.nio.file.Path", "java.nio.file.Path", "boolean"), static = true),
            TargetMethod("uninstallDynamicPlugin", listOf("javax.swing.JComponent", "com.intellij.ide.plugins.IdeaPluginDescriptorImpl", "boolean"), static = true),
            TargetMethod("installAndLoadDynamicPlugin", listOf("java.nio.file.Path", "com.intellij.ide.plugins.IdeaPluginDescriptorImpl"), static = true),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.InstalledPluginsState",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("getInstanceIfLoaded", emptyList(), static = true),
            TargetMethod("isRestartRequired", emptyList()),
            TargetMethod("setRestartRequired", listOf("boolean")),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.PluginDescriptorLoader",
        methods = listOf(TargetMethod("loadDescriptorFromArtifact", listOf("java.nio.file.Path", "com.intellij.openapi.util.BuildNumber"), static = true)),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.RepositoryHelper",
        methods = listOf(TargetMethod("loadPlugins", listOf("java.util.Set"), static = true)),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.openapi.updateSettings.impl.PluginDownloader",
        methods = listOf(
            TargetMethod("createDownloader", listOf("com.intellij.ide.plugins.IdeaPluginDescriptor"), static = true),
            TargetMethod("prepareToInstall", listOf("com.intellij.openapi.progress.ProgressIndicator")),
            TargetMethod("install", emptyList()),
            TargetMethod("installDynamically", listOf("javax.swing.JComponent")),
        ),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.openapi.extensions.PluginId",
        methods = listOf(TargetMethod("getId", listOf("java.lang.String"), static = true), TargetMethod("getIdString", emptyList())),
    ),
    TargetApi(
        category = "plugin-management",
        className = "com.intellij.ide.plugins.IdeaPluginDescriptor",
        methods = listOf(
            TargetMethod("getPluginId", emptyList()),
            TargetMethod("getName", emptyList()),
            TargetMethod("getVersion", emptyList()),
            TargetMethod("getVendor", emptyList()),
            TargetMethod("isEnabled", emptyList()),
            TargetMethod("isBundled", emptyList()),
            TargetMethod("isRequireRestart", emptyList()),
            TargetMethod("getPluginPath", emptyList()),
            TargetMethod("getDependencies", emptyList()),
        ),
    ),
    TargetApi(
        category = "debug-breakpoints",
        className = "com.intellij.xdebugger.XDebuggerManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getBreakpointManager", emptyList()),
            TargetMethod("getDebugSessions", emptyList()),
            TargetMethod("getCurrentSession", emptyList()),
        ),
    ),
    TargetApi(
        category = "debug-breakpoints",
        className = "com.intellij.xdebugger.breakpoints.XBreakpointManager",
        methods = listOf(
            TargetMethod("addLineBreakpoint", listOf("com.intellij.xdebugger.breakpoints.XLineBreakpointType", "java.lang.String", "int", "com.intellij.xdebugger.breakpoints.XBreakpointProperties", "boolean")),
            TargetMethod("removeBreakpoint", listOf("com.intellij.xdebugger.breakpoints.XBreakpoint")),
            TargetMethod("getAllBreakpoints", emptyList()),
            TargetMethod("findBreakpointAtLine", listOf("com.intellij.xdebugger.breakpoints.XLineBreakpointType", "com.intellij.openapi.vfs.VirtualFile", "int")),
            TargetMethod("findBreakpointsAtLine", listOf("com.intellij.xdebugger.breakpoints.XLineBreakpointType", "com.intellij.openapi.vfs.VirtualFile", "int")),
        ),
    ),
    TargetApi(
        category = "debug-breakpoints",
        className = "com.intellij.xdebugger.breakpoints.XBreakpointType",
        methods = listOf(
            TargetMethod("getId", emptyList()),
            TargetMethod("getTitle", emptyList()),
            TargetMethod("getSourcePosition", listOf("com.intellij.xdebugger.breakpoints.XBreakpoint")),
        ),
    ),
    TargetApi(
        category = "debug-breakpoints",
        className = "com.intellij.xdebugger.breakpoints.XLineBreakpointType",
        methods = listOf(
            TargetMethod("canPutAt", listOf("com.intellij.openapi.vfs.VirtualFile", "int", "com.intellij.openapi.project.Project")),
            TargetMethod("createBreakpointProperties", listOf("com.intellij.openapi.vfs.VirtualFile", "int")),
            TargetMethod("getDisplayText", listOf("com.intellij.xdebugger.breakpoints.XLineBreakpoint")),
        ),
    ),
    TargetApi(
        category = "debug-breakpoints",
        className = "com.intellij.xdebugger.breakpoints.XBreakpoint",
        methods = listOf(
            TargetMethod("isEnabled", emptyList()),
            TargetMethod("setEnabled", listOf("boolean")),
            TargetMethod("getType", emptyList()),
            TargetMethod("getSuspendPolicy", emptyList()),
            TargetMethod("getConditionExpression", emptyList()),
            TargetMethod("getTimeStamp", emptyList()),
        ),
    ),
    TargetApi(
        category = "debug-breakpoints",
        className = "com.intellij.xdebugger.breakpoints.XLineBreakpoint",
        methods = listOf(
            TargetMethod("getLine", emptyList()),
            TargetMethod("getFileUrl", emptyList()),
            TargetMethod("getPresentableFilePath", emptyList()),
            TargetMethod("isTemporary", emptyList()),
            TargetMethod("setTemporary", listOf("boolean")),
        ),
    ),
    TargetApi(
        category = "intentions-quickfixes",
        className = "com.intellij.codeInsight.intention.IntentionManager",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getIntentionActions", emptyList()),
            TargetMethod("getAvailableIntentions", emptyList()),
            TargetMethod("convertToFix", listOf("com.intellij.codeInsight.intention.IntentionAction")),
        ),
    ),
    TargetApi(
        category = "intentions-quickfixes",
        className = "com.intellij.codeInsight.intention.IntentionAction",
        methods = listOf(
            TargetMethod("getText", emptyList()),
            TargetMethod("isAvailable", listOf("com.intellij.openapi.project.Project", "com.intellij.openapi.editor.Editor", "com.intellij.psi.PsiFile")),
            TargetMethod("invoke", listOf("com.intellij.openapi.project.Project", "com.intellij.openapi.editor.Editor", "com.intellij.psi.PsiFile")),
            TargetMethod("startInWriteAction", emptyList()),
        ),
    ),
    TargetApi(
        category = "diagnostics-inspections",
        className = "com.intellij.codeInsight.daemon.DaemonCodeAnalyzer",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("isHighlightingAvailable", listOf("com.intellij.psi.PsiFile")),
            TargetMethod("restart", emptyList()),
            TargetMethod("restart", listOf("com.intellij.psi.PsiFile")),
        ),
    ),
    TargetApi(
        category = "diagnostics-inspections",
        className = "com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl",
        methods = listOf(
            TargetMethod("getHighlights", listOf("com.intellij.openapi.editor.Document", "com.intellij.lang.annotation.HighlightSeverity", "com.intellij.openapi.project.Project"), static = true),
            TargetMethod("isAllAnalysisFinished", listOf("com.intellij.psi.PsiFile")),
        ),
    ),
    TargetApi(
        category = "diagnostics-inspections",
        className = "com.intellij.codeInsight.daemon.impl.HighlightInfo",
        methods = listOf(
            TargetMethod("getDescription", emptyList()),
            TargetMethod("getSeverity", emptyList()),
            TargetMethod("getInspectionToolId", emptyList()),
            TargetMethod("getStartOffset", emptyList()),
            TargetMethod("getEndOffset", emptyList()),
        ),
    ),
    TargetApi(
        category = "diagnostics-inspections",
        className = "com.intellij.profile.codeInspection.InspectionProjectProfileManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getInspectionProfile", emptyList()),
        ),
    ),
    TargetApi(
        category = "diagnostics-inspections",
        className = "com.intellij.codeInspection.ex.GlobalInspectionContextBase",
        methods = listOf(
            TargetMethod("doInspections", listOf("com.intellij.analysis.AnalysisScope")),
            TargetMethod("getTools", emptyList()),
            TargetMethod("getUsedTools", emptyList()),
            TargetMethod("codeCleanup"),
        ),
    ),
    TargetApi(
        category = "duplicates",
        className = "com.intellij.dupLocator.DuplicatesProfile",
        methods = listOf(
            TargetMethod("getAllProfiles", emptyList(), static = true),
            TargetMethod("findProfileForLanguage", listOf("com.intellij.lang.Language"), static = true),
            TargetMethod("createVisitor", listOf("com.intellij.dupLocator.treeHash.FragmentsCollector")),
            TargetMethod("getDuplocatorState", listOf("com.intellij.lang.Language")),
            TargetMethod("supportDuplicatesIndex", emptyList()),
        ),
    ),
    TargetApi(
        category = "duplicates",
        className = "com.intellij.dupLocator.LightDuplicateProfile",
        methods = listOf(
            TargetMethod("process", listOf("com.intellij.lang.LighterAST", "com.intellij.dupLocator.LightDuplicateProfile\$Callback")),
            TargetMethod("acceptsFile", listOf("com.intellij.openapi.vfs.VirtualFile")),
        ),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.RefactoringFactory",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("createRename", listOf("com.intellij.psi.PsiElement", "java.lang.String")),
            TargetMethod("createRename", listOf("com.intellij.psi.PsiElement", "java.lang.String", "boolean", "boolean")),
            TargetMethod("createSafeDelete", listOf("[Lcom.intellij.psi.PsiElement;")),
        ),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.rename.RenameProcessor",
        methods = listOf(
            TargetMethod("findUsages", emptyList()),
            TargetMethod("performRefactoring", listOf("[Lcom.intellij.usageView.UsageInfo;")),
            TargetMethod("setSearchInComments", listOf("boolean")),
            TargetMethod("setSearchTextOccurrences", listOf("boolean")),
        ),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.usageView.UsageInfo",
        methods = listOf(
            TargetMethod("getElement", emptyList()),
            TargetMethod("getVirtualFile", emptyList()),
            TargetMethod("getSegment", emptyList()),
            TargetMethod("isValid", emptyList()),
            TargetMethod("isNonCodeUsage", emptyList()),
        ),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.extractMethod.ExtractMethodHandler",
        requiredInPlatformRuntime = false,
        methods = listOf(
            TargetMethod("invoke", listOf("com.intellij.openapi.project.Project", "com.intellij.openapi.editor.Editor", "com.intellij.psi.PsiFile", "com.intellij.openapi.actionSystem.DataContext")),
            TargetMethod("invoke", listOf("com.intellij.openapi.project.Project", "[Lcom.intellij.psi.PsiElement;", "com.intellij.openapi.actionSystem.DataContext")),
            TargetMethod("getElements", static = true),
            TargetMethod("getProcessor", static = true),
        ),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.extractclass.ExtractClassHandler",
        requiredInPlatformRuntime = false,
        methods = listOf(TargetMethod("invoke"), TargetMethod("isEnabledOnElements"), TargetMethod("getRefactoringName", emptyList(), static = true)),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.extractInterface.ExtractInterfaceHandler",
        requiredInPlatformRuntime = false,
        methods = listOf(TargetMethod("invoke"), TargetMethod("isEnabledOnElements"), TargetMethod("getRefactoringName", emptyList(), static = true)),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.changeSignature.ChangeSignatureHandler",
        methods = listOf(TargetMethod("findTargetMember"), TargetMethod("invoke"), TargetMethod("getTargetNotFoundMessage")),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.introduceVariable.IntroduceVariableHandler",
        requiredInPlatformRuntime = false,
        methods = listOf(TargetMethod("invoke"), TargetMethod("generatePreview")),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.introduceField.IntroduceFieldHandler",
        requiredInPlatformRuntime = false,
        methods = listOf(TargetMethod("invoke"), TargetMethod("getRefactoringNameText", emptyList(), static = true)),
    ),
    TargetApi(
        category = "refactoring",
        className = "com.intellij.refactoring.safeDelete.SafeDeleteProcessor",
        methods = listOf(TargetMethod("createInstance", static = true), TargetMethod("findUsages"), TargetMethod("performRefactoring")),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.RunManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getAllSettings", emptyList()),
            TargetMethod("getAllConfigurationsList", emptyList()),
            TargetMethod("getSelectedConfiguration", emptyList()),
            TargetMethod("setSelectedConfiguration", listOf("com.intellij.execution.RunnerAndConfigurationSettings")),
            TargetMethod("findConfigurationByName", listOf("java.lang.String")),
            TargetMethod("createConfiguration", listOf("java.lang.String", "com.intellij.execution.configurations.ConfigurationFactory")),
            TargetMethod("createConfiguration", listOf("com.intellij.execution.configurations.RunConfiguration", "com.intellij.execution.configurations.ConfigurationFactory")),
            TargetMethod("getConfigurationTemplate", listOf("com.intellij.execution.configurations.ConfigurationFactory")),
            TargetMethod("addConfiguration", listOf("com.intellij.execution.RunnerAndConfigurationSettings")),
            TargetMethod("removeConfiguration", listOf("com.intellij.execution.RunnerAndConfigurationSettings")),
            TargetMethod("setTemporaryConfiguration", listOf("com.intellij.execution.RunnerAndConfigurationSettings")),
            TargetMethod("suggestUniqueName", listOf("java.lang.String", "com.intellij.execution.configurations.ConfigurationType")),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.RunnerAndConfigurationSettings",
        methods = listOf(
            TargetMethod("getType", emptyList()),
            TargetMethod("getFactory", emptyList()),
            TargetMethod("getConfiguration", emptyList()),
            TargetMethod("getName", emptyList()),
            TargetMethod("setName", listOf("java.lang.String")),
            TargetMethod("getUniqueID", emptyList()),
            TargetMethod("setTemporary", listOf("boolean")),
            TargetMethod("checkSettings", emptyList()),
            TargetMethod("checkSettings", listOf("com.intellij.execution.Executor")),
            TargetMethod("setEditBeforeRun", listOf("boolean")),
            TargetMethod("setActivateToolWindowBeforeRun", listOf("boolean")),
            TargetMethod("setFocusToolWindowBeforeRun", listOf("boolean")),
            TargetMethod("storeInLocalWorkspace", emptyList()),
            TargetMethod("storeInDotIdeaFolder", emptyList()),
            TargetMethod("storeInArbitraryFileInProject", listOf("java.lang.String")),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.configurations.ConfigurationType",
        methods = listOf(
            TargetMethod("getId", emptyList()),
            TargetMethod("getDisplayName", emptyList()),
            TargetMethod("getConfigurationTypeDescription", emptyList()),
            TargetMethod("getConfigurationFactories", emptyList()),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.configurations.ConfigurationFactory",
        methods = listOf(
            TargetMethod("getId", emptyList()),
            TargetMethod("getName", emptyList()),
            TargetMethod("getType", emptyList()),
            TargetMethod("isApplicable", listOf("com.intellij.openapi.project.Project")),
            TargetMethod("createTemplateConfiguration", listOf("com.intellij.openapi.project.Project")),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.configurations.RunConfiguration",
        methods = listOf(
            TargetMethod("setName", listOf("java.lang.String")),
            TargetMethod("clone", emptyList()),
            TargetMethod("checkConfiguration", emptyList()),
            TargetMethod("isAllowRunningInParallel", emptyList()),
            TargetMethod("setAllowRunningInParallel", listOf("boolean")),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.ExecutionManager",
        methods = listOf(
            TargetMethod("getInstance", listOf("com.intellij.openapi.project.Project"), static = true),
            TargetMethod("getRunningProcesses", emptyList()),
            TargetMethod("restartRunProfile"),
            TargetMethod("getContentManager", emptyList()),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.ProgramRunnerUtil",
        methods = listOf(
            TargetMethod("executeConfiguration", listOf("com.intellij.openapi.project.Project", "com.intellij.execution.RunnerAndConfigurationSettings", "com.intellij.execution.Executor"), static = true),
            TargetMethod("executeConfigurationAsync", static = true),
            TargetMethod("getRunner", static = true),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.ExecutorRegistry",
        methods = listOf(
            TargetMethod("getInstance", emptyList(), static = true),
            TargetMethod("getExecutorById", listOf("java.lang.String")),
        ),
    ),
    TargetApi(
        category = "run-build-test",
        className = "com.intellij.execution.process.ProcessHandler",
        methods = listOf(
            TargetMethod("destroyProcess", emptyList()),
            TargetMethod("isProcessTerminated", emptyList()),
            TargetMethod("isProcessTerminating", emptyList()),
            TargetMethod("getExitCode", emptyList()),
        ),
    ),
)
